# Generated by Django 5.2.8 on 2025-11-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='delivered',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='from_user',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='time',
            field=models.CharField(max_length=50),
        ),
    ]
